name: Build Zed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: zed-industries/zed

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add WASM target
      run: rustup target add wasm32-wasi

    - name: Install C++ build tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Run cargo
      run: cargo build --release

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: zed
        path: target\release\Zed.exe
