name: Build Zed

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: zed-industries/zed

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add WASM target
      run: rustup target add wasm32-wasi
      
#    - name: Add add x86_64-pc-windows-msvc taget
#      run: rustup target add x86_64-pc-windows-msvc

    - name: Install C++ build tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Run cargo
#      run: cargo run --release --target x86_64-pc-windows-msvc
      run: cargo run --release

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target
